name = "dex-screen-streaming"
main = "src/index.ts"
compatibility_date = "2025-12-12"

[durable_objects]
bindings = [{ name = "ROOMS", class_name = "RoomDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]
